### ISSUE TITLE
Needs https://github.com/ipfs/get-gh-contributors fetch feature

### ISSUE THREAD

**Issue by daviddias** [ipfs-shipyard/contributors#3]
We need to move https://github.com/ipfs/get-gh-contributors fetch feature to here, so that this service doesn't depend on yet another service and just queries gh api directly.

**Comment by alanshaw** [comment]
FWIW, I quite like that it is a separate service that this project consumes. I think it's good that it can be maintained, versioned and deployed separately.

**Comment by lgierth** [comment]
But someone has to run it, and that unfortunately usually defaults to myself :) We can keep some level of separation by having get-gh-contributors being a CLI tool installed through NPM.
