### ISSUE TITLE
Missing howto add another org as an option

### ISSUE THREAD

**Issue by daviddias** [ipfs-shipyard/contributors#5]
> https://github.com/ipfs/contribs#examples

The readme only shows how to fetch from a org that has already been selected or _all_, but doesn't show how to add more orgs (for example ipfs-shipyarD)

**Comment by alanshaw** [comment]
The [usage instructions for the CLI](https://github.com/ipfs/contributors/blob/master/scripts/bin/create.usage.txt#L7-L8) specify that the available orgs are documented in the get-gh-contributors repo. The usage instructions are linked from the README and available in the CLI if you pass the `--help` or `--usage` flag.

So...the orgs that are available are the orgs available in the get-gh-contributors API. You can add an org to get-gh-contributors and you'd be able to use it here.

Also of note, you currently can't add contributors from multiple orgs into one contributors page.
